GET http://localhost:3019/players/
###

GET http://localhost:3019/players/1/

###
POST http://localhost:3019/players/
Content-type:application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}


### 
PUT http://localhost:3019/players/13/
content-type:application/json

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}

###

DELETE http://localhost:3019/players/2/


